<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
	<modelVersion>4.1.0</modelVersion>

	<parent>
		<groupId>ch.scaille</groupId>
		<artifactId>skylib-starter-parent</artifactId>
		<version>${starter.revision}</version>
		<relativePath />
	</parent>
	<groupId>ch.scaille.tcwriter</groupId>
	<artifactId>testcase-writer</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<subprojects>
		<subproject>api</subproject>
		<subproject>model</subproject>
		<subproject>core</subproject>
		<subproject>javatc</subproject>
		<subproject>flowtc</subproject>
		<subproject>maven-plugin</subproject>
		<subproject>gui</subproject>
		<subproject>gui-it</subproject>
		<subproject>examples</subproject>
		<subproject>webapp</subproject>
	</subprojects>
	<properties>
		<java.version>25</java.version>

		<sonar.exclusions>**/node_modules/**,**/generated/**</sonar.exclusions>
	</properties>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>2.10</version>
				<configuration>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<incrementalCompilation>classes</incrementalCompilation>
						<debuglevel>all</debuglevel>
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${lombok.version}</version>
							</path>
						</annotationProcessorPaths>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>aspectj-maven-plugin</artifactId>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<complianceLevel>${java.version}</complianceLevel>
						<encoding>${project.build.sourceEncoding}</encoding>
						<Xlint>ignore</Xlint>
						<verbose>true</verbose>

						<forceAjcCompile>true</forceAjcCompile>
						<sources />
						<weaveDirectories>
							<weaveDirectory>${project.build.directory}/classes</weaveDirectory>
						</weaveDirectories>
					</configuration>
					<executions>
						<execution>
							<id>aop sources</id>
							<phase>compile</phase>
							<goals>
								<goal>compile</goal>
							</goals>
						</execution>
						<execution>
							<id>aop test sources</id>
							<phase>test-compile</phase>
							<goals>
								<goal>test-compile</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<executions>
						<execution>
							<id>default</id>
							<phase>none</phase>
						</execution>
						<execution>
							<id>single</id>
							<phase>package</phase>
							<goals>
								<goal>single</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<appendAssemblyId>false</appendAssemblyId>
						<attach>false</attach>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-model</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-core</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-gui</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-examples</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-examples</artifactId>
				<classifier>fatjar</classifier>
				<version>${revision}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-javatc-core</artifactId>
				<version>${revision}</version>
				<exclusions>
					<exclusion>
						<groupId>ch.scaille.tcwriter</groupId>
						<artifactId>testcase-writer-javatc-client</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-console-standalone</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-javatc-core</artifactId>
				<classifier>client-bundle</classifier>
				<version>${revision}</version>
				<type>zip</type>
				<scope>runtime</scope>
				<exclusions>
					<exclusion>
						<groupId>ch.scaille.tcwriter</groupId>
						<artifactId>testcase-writer-javatc-client</artifactId>
					</exclusion>
					<exclusion>
						<groupId>ch.scaille.tcwriter</groupId>
						<artifactId>testcase-writer-javatc-recorder</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-console-standalone</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-javatc-client</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-javatc-client</artifactId>
				<classifier>fatjar</classifier>
				<version>${revision}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>ch.scaille.tcwriter</groupId>
				<artifactId>testcase-writer-javatc-recorder</artifactId>
				<version>${revision}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>ch.scaille</groupId>
			<artifactId>lib-testing-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>
</project>
