<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent/>
    <artifactId>lib-testing-selenium-test-page</artifactId>

    <properties>
        <surefireArgLine>@{argLine} --add-opens
            org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote=org.seleniumhq.selenium.apia
        </surefireArgLine>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ch.scaille</groupId>
            <artifactId>gui-pilot-selenium</artifactId>
        </dependency>

        <dependency>
            <groupId>ch.scaille</groupId>
            <artifactId>lib-utils</artifactId>
        </dependency>

        <!-- http server -->
        <dependency>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-core</artifactId>
            <type>modular-jar</type>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
	            <configuration>
                    <!-- MAVEN4 HACK -->
                    <additionalClasspathDependencies>        <dependency>
                        <groupId>io.undertow</groupId>
                        <artifactId>undertow-core</artifactId>
                        <version>${undertow.version}</version>
                    </dependency>
                    </additionalClasspathDependencies>
				</configuration>
			</plugin>
        </plugins>
    </build>
</project>
