openapi: 3.0.0
info:
  title: Test Case Server
  version: 0.0.1
servers: 
  - url: http://localhost:8080/api/
paths:
  /dictionary:
    $ref: paths/allDictionaries.yaml
  /dictionary/current:
    $ref: paths/currentDictionary.yaml
  /testcase:
    $ref: paths/allTestCases.yaml
  /testcase/current:
    $ref: paths/currentTestCase.yaml
  /context:
    $ref: paths/context.yaml
components:
  schemas:
    Context:
      $ref: schemas/Context.yaml#/Context
    ContextUpdate:
      $ref: schemas/Context.yaml#/ContextUpdate
    Metadata:
      $ref: schemas/Metadata.yaml#/Metadata
    TestDictionary:
      $ref: schemas/TestDictionary.yaml#/TestDictionary
    TestCase:
      $ref: schemas/TestCase.yaml#/TestCase


