openapi: 3.1.0
info:
  title: Test Case Server
  version: 0.0.1
servers: 
  - url: http://localhost:3000
paths:
  /dictionary:
    $ref: paths/allDictionaries.yaml
  /dictionary/current:
    $ref: paths/currentDictionary.yaml
  /context:
    $ref: paths/context.yaml
components:
  schemas:
    Context:
      $ref: schemas/Context.yaml#/Context
    ContextUpdate:
      $ref: schemas/Context.yaml#/ContextUpdate
    Metadata:
      $ref: schemas/Metadata.yaml#/Metadata
    TestDictionary:
      $ref: schemas/TestDictionary.yaml#/TestDictionary


