openapi: 3.0.0
info:
  title: Test Case Server
  version: 0.0.1
servers: 
  - url: http://localhost:8080/api
paths:
  /dictionary:
    $ref: 'paths/allDictionaries.yaml'
  /dictionary/current:
    $ref: paths/currentDictionary.yaml
  /testcase:
    $ref: paths/allTestCases.yaml
  /testcase/{tc}:
    $ref: paths/testCase.yaml
  /testcase/{tc}/execute:
    $ref: paths/executeTestCase.yaml
  /context:
    $ref: paths/context.yaml
components:
  schemas:
    Context:
      $ref: schemas/Context.yaml#/Context
    ContextUpdate:
      $ref: schemas/Context.yaml#/ContextUpdate
    Metadata:
      $ref: schemas/Metadata.yaml#/Metadata
    TestDictionary:
      $ref: schemas/TestDictionary.yaml#/TestDictionary
    TestCase:
      $ref: schemas/TestCase.yaml#/TestCase
    TestStatus:
      $ref: schemas/StepStatus.yaml#/StepStatus


