<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ch.scaille.tcwriter</groupId>
		<artifactId>testcase-writer</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>testcase-writer-gui</artifactId>

	<dependencies>
		<dependency>
			<groupId>ch.scaille.tcwriter</groupId>
			<artifactId>testcase-writer-javatc-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.scaille.tcwriter</groupId>
			<artifactId>testcase-writer-javatc-core</artifactId>
			<classifier>client-bundle</classifier>
			<type>zip</type>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>ch.scaille</groupId>
			<artifactId>lib-gui</artifactId>
		</dependency>
		<!-- swing graphic assets -->
		<dependency>
			<groupId>net.java.linoleum</groupId>
			<artifactId>jlfgr</artifactId>
			<version>1_0</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>tc-resources</finalName>
					<descriptors>
						<descriptor>src/assembly/tc-resources.xml</descriptor>
					</descriptors>
					<workDirectory>${project.build}</workDirectory>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
