openapi: 3.0.3
info:
  title: Test Case Server
  version: 0.0.0
servers: 
  - url: /v0
paths:
  /dictionary:
    $ref: 'paths/allDictionaries.yaml'
  /dictionary/{dictionary}:
    $ref: paths/dictionary.yaml
  /testcase:
    $ref: paths/allTestCases.yaml
  /testcase/{tc}:
    $ref: paths/testCase.yaml
  /testcase/{tc}/execute:
    $ref: paths/executeTestCase.yaml
  /testcase/{tc}/export:
    $ref: paths/exportTestCase.yaml
  /context:
    $ref: paths/context.yaml
components:
  schemas:
    Context:
      $ref: schemas/Context.yaml#/Context
    Metadata:
      $ref: schemas/Metadata.yaml#/Metadata
    IdObject:
      $ref: schemas/Metadata.yaml#/IdObject
    NamedObject:
      $ref: schemas/Metadata.yaml#/NamedObject
    TestDictionary:
      $ref: schemas/TestDictionary.yaml#/TestDictionary
    StepClassifier:
      $ref: schemas/TestDictionary.yaml#/StepClassifier
    TestParameterFactory:
      $ref: schemas/TestDictionary.yaml#/TestParameterFactory
    TestCase:
      $ref: schemas/TestCase.yaml#/TestCase
    TestStatus:
      $ref: schemas/StepStatus.yaml#/StepStatus
    ExportType:
      $ref: schemas/ExportType.yaml#/ExportType

